NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.manufacturer.auto.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.manufacturer.auto.com-cert.pem
    OrganizationalUnitIdentifier: peer
