version: '2'

services:

  orderer.auto.com:
    container_name: orderer.auto.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=false

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp:/var/hyperledger/orderer/msp
    - orderer.auto.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.manufacturer.auto.com:
    container_name: peer0.manufacturer.auto.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_ID=peer0.manufacturer.auto.com
      - CORE_PEER_ADDRESS=peer0.manufacturer.auto.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.manufacturer.auto.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manufacturer.auto.com:7051
      - CORE_PEER_LOCALMSPID=ManufacturerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/manufacturer.auto.com/peers/peer0.manufacturer.auto.com/msp:/etc/hyperledger/fabric/msp
        - peer0.manufacturer.auto.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053
      - 7055:6060
  

  peer0.dealer.auto.com:
    container_name: peer0.dealer.auto.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_ID=peer0.dealer.auto.com
      - CORE_PEER_ADDRESS=peer0.dealer.auto.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.dealer.auto.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.dealer.auto.com:7051
      - CORE_PEER_LOCALMSPID=DealerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/dealer.auto.com/peers/peer0.dealer.auto.com/msp:/etc/hyperledger/fabric/msp
        - peer0.dealer.auto.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053
      - 8055:6060

  
  peer0.mvd.auto.com:
    container_name: peer0.mvd.auto.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_ID=peer0.mvd.auto.com
      - CORE_PEER_ADDRESS=peer0.mvd.auto.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.mvd.auto.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mvd.auto.com:7051
      - CORE_PEER_LOCALMSPID=MvdMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/mvd.auto.com/peers/peer0.mvd.auto.com/msp:/etc/hyperledger/fabric/msp
        - peer0.mvd.auto.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053
      - 9055:6060