NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.mvd.auto.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.mvd.auto.com-cert.pem
    OrganizationalUnitIdentifier: peer
