# configtx

#   CAPABILITIES
Capabilities:
  Application: &ApplicationCapabilities
    V1_3: true
  Orderer: &OrdererCapabilities
    V1_1: true
  Channel: &ChannelCapabilities
    V1_3: true

# ORGANIZATIONS
Organizations:
  - &Orderer
    Name: Orderer
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/auto.com/msp
    Policies: &OrdererPolicies
      Readers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('OrdererMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('OrdererMSP.admin')"

  - &Manufacturer
    Name: Manufacturer
    ID: ManufacturerMSP
    MSPDir: ./crypto-config/peerOrganizations/manufacturer.auto.com/msp
    Policies: &ManufacturerPolicies
      Readers:
          Type: Signature
          Rule: "OR('ManufacturerMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('ManufacturerMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('ManufacturerMSP.admin')"
    AnchorPeers:
      - Host: peer0.manufacturer.auto.com
        Port: 7051
      # You may add additional hosts here

  - &Dealer
    Name: Dealer
    ID: DealerMSP
    MSPDir: ./crypto-config/peerOrganizations/dealer.auto.com/msp
    Policies: &DealerPolicies
      Readers:
          Type: Signature
          Rule: "OR('DealerMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('DealerMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('DealerMSP.admin')"
    AnchorPeers:
      - Host: peer0.dealer.auto.com
        Port: 7051

  - &Mvd
    Name: Mvd
    ID: MvdMSP
    MSPDir: ./crypto-config/peerOrganizations/mvd.auto.com/msp
    Policies: &MvdPolicies
      Readers:
          Type: Signature
          Rule: "OR('MvdMSP.member')"
      Writers:
          Type: Signature
          Rule: "OR('MvdMSP.member')"
      Admins:
          Type: Signature
          Rule: "OR('MvdMSP.admin')"
    AnchorPeers:
      - Host: peer0.mvd.auto.com
        Port: 7051
  
# ORDERER
Orderer: &OrdererDefaults

  OrdererType: solo

  Addresses:
    - orderer.auto.com:7050

    # Policies for Orderer
  Policies:
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta  
        Rule: "MAJORITY Admins"

    # BlockValidation specifies what signatures must be included in the block
    # from the orderer for the peer to validate it.
    BlockValidation:
        Type: ImplicitMeta
        Rule: "ANY Writers"

  # Batch Timeout: The amount of time to wait before creating a batch
  BatchTimeout: 2s

  # Batch Size: Controls the number of messages batched into a block
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB



  Capabilities:
    <<: *OrdererCapabilities

Application: &ApplicationDefaults

  ACLs: &ACLsDefault
    
    # ACL policy for lscc's "getid" function
    lscc/ChaincodeExists: /Channel/Application/Readers

    # ACL policy for lscc's "getdepspec" function
    lscc/GetDeploymentSpec: /Channel/Application/Readers

    # ACL policy for lscc's "getccdata" function
    lscc/GetChaincodeData: /Channel/Application/Readers

    # ACL Policy for lscc's "getchaincodes" function
    #    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
    lscc/GetInstantiatedChaincodes: /Channel/Application/StrictAdminPolicy

    #---Query System Chaincode (qscc) function to policy mapping for access control---#

    # ACL policy for qscc's "GetChainInfo" function
    # qscc/GetChainInfo: /Channel/Application/Readers
    qscc/GetChainInfo: /Channel/Application/StrictAdminPolicy

    # ACL policy for qscc's "GetBlockByNumber" function
    qscc/GetBlockByNumber: /Channel/Application/Readers

    # ACL policy for qscc's  "GetBlockByHash" function
    qscc/GetBlockByHash: /Channel/Application/Readers

    # ACL policy for qscc's "GetTransactionByID" function
    qscc/GetTransactionByID: /Channel/Application/Readers

    # ACL policy for qscc's "GetBlockByTxID" function
    qscc/GetBlockByTxID: /Channel/Application/Readers

    #---Configuration System Chaincode (cscc) function to policy mapping for access control---#

    # ACL policy for cscc's "GetConfigBlock" function
    cscc/GetConfigBlock: /Channel/Application/Readers

    # ACL policy for cscc's "GetConfigTree" function
    cscc/GetConfigTree: /Channel/Application/Readers

    # ACL policy for cscc's "SimulateConfigTreeUpdate" function
    cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers

    #---Miscellanesous peer function to policy mapping for access control---#

    # ACL policy for invoking chaincodes on peer
    peer/Propose: /Channel/Application/Writers

    # ACL policy for chaincode to chaincode invocation
    peer/ChaincodeToChaincode: /Channel/Application/Readers

    #---Events resource to policy mapping for access control###---#

    # ACL policy for sending block events
    event/Block: /Channel/Application/Readers

    # ACL policy for sending filtered block events
    event/FilteredBlock: /Channel/Application/Readers

  # Default policies
  Policies: &ApplicationDefaultPolicies
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"

    StrictAdminPolicy:
        Type: ImplicitMeta
        Rule: "ANY Admins"
 
  Organizations:

  Capabilities:
    <<: *ApplicationCapabilities
 

#   CHANNEL
Channel: &ChannelDefaults
  Policies:
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        # Any admin can create a channel - if changed to MAJORITY then both orgs needed for creation
        Rule: "ANY Admins"

  Capabilities:

  
#   PROFILES
Profiles:

  AutoOrdererGenesis:
      <<: *ChannelDefaults
      Orderer:
          <<: *OrdererDefaults
          Organizations:
              - <<: *Orderer


      Application:
            <<: *ApplicationDefaults

            Organizations:
                - <<: *Manufacturer
                - <<: *Dealer  
                - <<: *Mvd               
                 

      Consortiums:

        AutoConsortium:
            
            Organizations:
                  - <<: *Manufacturer
                  - <<: *Dealer  
                  - <<: *Mvd                             
                
                  
  AutoChannel:
    <<: *ChannelDefaults
    Consortium: AutoConsortium
        
    Application:
        <<: *ApplicationDefaults
        
        Organizations:
            - <<: *Manufacturer
            - <<: *Dealer
            - <<: *Mvd
            
